export const dom = {
  app: document.querySelector('.app'),
  sidebar: document.querySelector('.sidebar'),
  noteList: document.getElementById('note-list'),
  noteTitle: document.getElementById('note-title'),
  noteContent: document.getElementById('note-content'),
  timestamp: document.getElementById('note-timestamp'),
  timerDisplay: document.getElementById('timer-display'),
  searchInput: document.getElementById('search-input'),
  newNoteBtn: document.getElementById('new-note-btn'),
  fontSizeInput: document.getElementById('font-size-input'),
  fontSizeValue: document.getElementById('font-size-value'),
  fontResetBtn: document.getElementById('font-reset-btn'),
  timerMinutesInput: document.getElementById('timer-minutes-input'),
  darkModeToggle: document.getElementById('dark-mode-toggle'),
  timerToggle: document.getElementById('timer-toggle'),
  timerStop: document.getElementById('timer-stop'),
  drawerToggle: document.getElementById('drawer-toggle'),
  sidebarHeader: document.getElementById('sidebar-header'),
  editorMetaRow: document.getElementById('editor-meta-row'),
  editorActions: document.querySelector('.editor__actions'),
  appOverlay: document.getElementById('app-overlay'),
};
